# SPDX-FileCopyrightText: 2025-2026 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = ["**/Cargo.lock", "pkg/aur/.SRCINFO", "**/.cargo/config.toml"]
SPDX-FileCopyrightText = "2025-2026 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["masterror-knowledge/src/errors/ownership/e0382.rs", "masterror-knowledge/src/errors/ownership/e0384.rs"]
SPDX-FileCopyrightText = "2025-2026 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"
