# SPDX-FileCopyrightText: 2025-2026 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = ["**/Cargo.lock", "pkg/aur/.SRCINFO", "masterror-cli/src/locale/ko.rs"]
SPDX-FileCopyrightText = "2025-2026 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"
